# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - zawasAppDocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://zawas.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_541ae1f0128c4800acf719d198c556a3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_81b24f7bb8f64b21b6b982c7a50c3e7b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: zawas.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_541ae1f0128c4800acf719d198c556a3 }}/zawasappdocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'zawasAppDocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a03e56c9d61746af8e33ce293423ee20 }}
        images: 'zawas.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_541ae1f0128c4800acf719d198c556a3 }}/zawasappdocker:${{ github.sha }}'